package cn.kgc.crowd.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pass.uid
     *
     * @mbg.generated Sat Aug 08 15:05:30 CST 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pass.uName
     *
     * @mbg.generated Sat Aug 08 15:05:30 CST 2020
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pass.uPassword
     *
     * @mbg.generated Sat Aug 08 15:05:30 CST 2020
     */
    private String upassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pass.admin
     *
     * @mbg.generated Sat Aug 08 15:05:30 CST 2020
     */
    private Integer admin;

    @Override
    public String toString() {
        return "User{" +
                "uid=" + uid +
                ", uname='" + uname + '\'' +
                ", upassword='" + upassword + '\'' +
                ", admin=" + admin +
                '}';
    }

    public Integer getUid() {
        return uid;
    }

    public void setUid(Integer uid) {
        this.uid = uid;
    }

    public String getUname() {
        return uname;
    }

    public void setUname(String uname) {
        this.uname = uname;
    }

    public String getUpassword() {
        return upassword;
    }

    public void setUpassword(String upassword) {
        this.upassword = upassword;
    }

    public Integer getAdmin() {
        return admin;
    }

    public void setAdmin(Integer admin) {
        this.admin = admin;
    }

    public User() {
    }

    public User(Integer uid, String uname, String upassword, Integer admin) {
        this.uid = uid;
        this.uname = uname;
        this.upassword = upassword;
        this.admin = admin;
    }
}