package cn.kgc.crowd.mapper;

import cn.kgc.crowd.entity.HuoDong;
import cn.kgc.crowd.entity.HuoDongExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.security.access.method.P;

public interface HuoDongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huodong
     *
     * @mbg.generated Wed Aug 12 11:49:38 CST 2020
     */
    long countByExample(HuoDongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huodong
     *
     * @mbg.generated Wed Aug 12 11:49:38 CST 2020
     */
    int deleteByExample(HuoDongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huodong
     *
     * @mbg.generated Wed Aug 12 11:49:38 CST 2020
     */
    int insert(HuoDong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huodong
     *
     * @mbg.generated Wed Aug 12 11:49:38 CST 2020
     */
    int insertSelective(HuoDong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huodong
     *
     * @mbg.generated Wed Aug 12 11:49:38 CST 2020
     */
    List<HuoDong> selectByExample(HuoDongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huodong
     *
     * @mbg.generated Wed Aug 12 11:49:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") HuoDong record, @Param("example") HuoDongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huodong
     *
     * @mbg.generated Wed Aug 12 11:49:38 CST 2020
     */
    int updateByExample(@Param("record") HuoDong record, @Param("example") HuoDongExample example);

    Integer savess(@Param("huodong") HuoDong huoDong);

}