package cn.kgc.crowd.mapper;

import cn.kgc.crowd.entity.Marriage;
import cn.kgc.crowd.entity.MarriageExample;
import java.util.List;

import cn.kgc.crowd.entity.ShengHuo;
import org.apache.ibatis.annotations.Param;

public interface MarriageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marriage
     *
     * @mbg.generated Wed Aug 12 08:38:06 CST 2020
     */
    long countByExample(MarriageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marriage
     *
     * @mbg.generated Wed Aug 12 08:38:06 CST 2020
     */
    int deleteByExample(MarriageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marriage
     *
     * @mbg.generated Wed Aug 12 08:38:06 CST 2020
     */
    int insert(Marriage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marriage
     *
     * @mbg.generated Wed Aug 12 08:38:06 CST 2020
     */
    int insertSelective(Marriage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marriage
     *
     * @mbg.generated Wed Aug 12 08:38:06 CST 2020
     */
    List<Marriage> selectByExample(MarriageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marriage
     *
     * @mbg.generated Wed Aug 12 08:38:06 CST 2020
     */
    int updateByExampleSelective(@Param("record") Marriage record, @Param("example") MarriageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marriage
     *
     * @mbg.generated Wed Aug 12 08:38:06 CST 2020
     */
    int updateByExample(@Param("record") Marriage record, @Param("example") MarriageExample example);

    Integer savedd(@Param("marriage") Marriage marriage);


}