package cn.kgc.crowd.mapper;

import cn.kgc.crowd.entity.ShengHuo;
import cn.kgc.crowd.entity.ShengHuoExample;

import java.awt.print.Book;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShengHuoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenghuo
     *
     * @mbg.generated Tue Aug 11 17:12:11 CST 2020
     */
    long countByExample(ShengHuoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenghuo
     *
     * @mbg.generated Tue Aug 11 17:12:11 CST 2020
     */
    int deleteByExample(ShengHuoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenghuo
     *
     * @mbg.generated Tue Aug 11 17:12:11 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenghuo
     *
     * @mbg.generated Tue Aug 11 17:12:11 CST 2020
     */

    int insert(ShengHuo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenghuo
     *
     * @mbg.generated Tue Aug 11 17:12:11 CST 2020
     */
    int insertSelective(ShengHuo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenghuo
     *
     * @mbg.generated Tue Aug 11 17:12:11 CST 2020
     */
    List<ShengHuo> selectByExample(ShengHuoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenghuo
     *
     * @mbg.generated Tue Aug 11 17:12:11 CST 2020
     */
    ShengHuo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenghuo
     *
     * @mbg.generated Tue Aug 11 17:12:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") ShengHuo record, @Param("example") ShengHuoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenghuo
     *
     * @mbg.generated Tue Aug 11 17:12:11 CST 2020
     */
    int updateByExample(@Param("record") ShengHuo record, @Param("example") ShengHuoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenghuo
     *
     * @mbg.generated Tue Aug 11 17:12:11 CST 2020
     */
    int updateByPrimaryKeySelective(ShengHuo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenghuo
     *
     * @mbg.generated Tue Aug 11 17:12:11 CST 2020
     */
    int updateByPrimaryKey(ShengHuo record);


    /*增加*/
    Integer save(@Param("shenghuo") ShengHuo shengHuo);
}