package cn.kgc.crowd.mapper;

import cn.kgc.crowd.entity.User;
import cn.kgc.crowd.entity.UserExample;

import java.awt.print.Book;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pass
     *
     * @mbg.generated Sat Aug 08 15:05:30 CST 2020
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pass
     *
     * @mbg.generated Sat Aug 08 15:05:30 CST 2020
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pass
     *
     * @mbg.generated Sat Aug 08 15:05:30 CST 2020
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pass
     *
     * @mbg.generated Sat Aug 08 15:05:30 CST 2020
     */

    /*注册用户*/
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pass
     *
     * @mbg.generated Sat Aug 08 15:05:30 CST 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pass
     *
     * @mbg.generated Sat Aug 08 15:05:30 CST 2020
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pass
     *
     * @mbg.generated Sat Aug 08 15:05:30 CST 2020
     */
    User selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pass
     *
     * @mbg.generated Sat Aug 08 15:05:30 CST 2020
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pass
     *
     * @mbg.generated Sat Aug 08 15:05:30 CST 2020
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pass
     *
     * @mbg.generated Sat Aug 08 15:05:30 CST 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pass
     *
     * @mbg.generated Sat Aug 08 15:05:30 CST 2020
     */
    int updateByPrimaryKey(User record);

    //登录
    public User getNameAndPassword(@Param("uname")String uname,@Param("upassword") String upassword);


    /*增加*/
   /* Integer save(@Param("user") User user);*/
    boolean register(@Param("uname") String uname, @Param("upassword") String upassword);

    int findUserByLgName( String uname);




    /*查询一个*/
    User getById(@Param("id") int id);

    /*修改密码*/
    Integer update(@Param("user") User user);

}