package cn.kgc.crowd.mapper;

import cn.kgc.crowd.entity.ShengHuo;
import cn.kgc.crowd.entity.Work;
import cn.kgc.crowd.entity.WorkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Tue Aug 11 18:51:55 CST 2020
     */
    long countByExample(WorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Tue Aug 11 18:51:55 CST 2020
     */
    int deleteByExample(WorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Tue Aug 11 18:51:55 CST 2020
     */
    int insert(Work record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Tue Aug 11 18:51:55 CST 2020
     */
    int insertSelective(Work record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Tue Aug 11 18:51:55 CST 2020
     */
    List<Work> selectByExample(WorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Tue Aug 11 18:51:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") Work record, @Param("example") WorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Tue Aug 11 18:51:55 CST 2020
     */
    int updateByExample(@Param("record") Work record, @Param("example") WorkExample example);



    Integer saves(@Param("work") Work work);


}